# Generated by Django 5.0.6 on 2024-10-21 17:08

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Appuser",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("first_name", models.CharField(max_length=500)),
                ("last_name", models.CharField(max_length=500)),
                ("country", models.CharField(max_length=500)),
                ("phone_no", models.CharField(max_length=500)),
                ("password", models.CharField(max_length=500)),
                ("created_at", models.DateTimeField(null=True)),
                ("updated_at", models.DateTimeField(null=True)),
                ("login_at", models.DateTimeField(null=True)),
                ("logout_at", models.DateTimeField(null=True)),
            ],
        ),
    ]
