# Generated by Django 5.0.6 on 2024-10-21 17:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("petapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="appuser",
            name="profile_img",
            field=models.CharField(max_length=500, null=True),
        ),
    ]
