# Generated by Django 5.0.6 on 2024-10-21 17:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("petapp", "0002_appuser_profile_img"),
    ]

    operations = [
        migrations.AddField(
            model_name="appuser",
            name="email",
            field=models.CharField(default="", max_length=500),
            preserve_default=False,
        ),
    ]
