# Generated by Django 5.0.6 on 2024-11-03 11:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("petapp", "0003_appuser_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appuser",
            name="profile_img",
            field=models.ImageField(null=True, upload_to="profile_pic/"),
        ),
    ]
