# Generated by Django 4.1.13 on 2024-11-10 19:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("petapp", "0005_logout"),
    ]

    operations = [
        migrations.CreateModel(
            name="category",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name="userpet",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("images", models.JSONField(default=list)),
                ("name", models.CharField(max_length=500)),
                ("price", models.CharField(max_length=500)),
                ("location", models.CharField(max_length=500)),
                ("address", models.CharField(max_length=500)),
                ("whatsapp_no", models.CharField(max_length=500)),
                ("description", models.CharField(max_length=500, null=True)),
                ("created_at", models.DateTimeField(null=True)),
                ("updated_at", models.DateTimeField(null=True)),
                ("deleted_at", models.DateTimeField(null=True)),
                ("delete", models.BooleanField(default=False)),
                (
                    "categ_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="petapp.category",
                    ),
                ),
                (
                    "user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="petapp.appuser"
                    ),
                ),
            ],
        ),
    ]
