# Generated by Django 4.1.13 on 2024-11-14 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("petapp", "0006_category_userpet"),
    ]

    operations = [
        migrations.AddField(
            model_name="userpet",
            name="age",
            field=models.CharField(default=1, max_length=500),
        ),
        migrations.AddField(
            model_name="userpet",
            name="breed",
            field=models.CharField(default="Original", max_length=500),
        ),
        migrations.AddField(
            model_name="userpet",
            name="sex",
            field=models.CharField(default="Male", max_length=500),
        ),
    ]
