# Generated by Django 4.1.13 on 2024-11-17 20:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("petapp", "0007_userpet_age_userpet_breed_userpet_sex"),
    ]

    operations = [
        migrations.CreateModel(
            name="Favourite",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("status", models.BooleanField(null=True)),
                (
                    "pet_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="petapp.userpet"
                    ),
                ),
                (
                    "user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="petapp.appuser"
                    ),
                ),
            ],
        ),
    ]
