# Generated by Django 4.1.13 on 2024-11-24 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("petapp", "0008_favourite"),
    ]

    operations = [
        migrations.AddField(
            model_name="userpet",
            name="status",
            field=models.CharField(default="Sale", max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="userpet",
            name="price",
            field=models.CharField(max_length=500, null=True),
        ),
    ]
