# Generated by Django 4.1.13 on 2024-11-24 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("petapp", "0009_userpet_status_alter_userpet_price"),
    ]

    operations = [
        migrations.CreateModel(
            name="Find_Lost_Pet",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=500, null=True)),
                ("images", models.JSONField(default=list)),
                ("age", models.CharField(max_length=500, null=True)),
                ("breed", models.CharField(max_length=500, null=True)),
                ("sex", models.CharField(max_length=500, null=True)),
                ("color", models.CharField(max_length=500, null=True)),
                ("identity_mark", models.CharField(max_length=500, null=True)),
                ("status", models.CharField(max_length=500, null=True)),
                ("person_name", models.CharField(max_length=500)),
                ("address", models.CharField(max_length=500, null=True)),
                ("location", models.CharField(max_length=500, null=True)),
                ("phone_no", models.CharField(max_length=500, null=True)),
                ("description", models.CharField(max_length=500, null=True)),
                ("created_at", models.DateTimeField(null=True)),
                ("updated_at", models.DateTimeField(null=True)),
                ("delete", models.BooleanField(default=False, null=True)),
                (
                    "categ_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="petapp.category",
                    ),
                ),
                (
                    "user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="petapp.appuser"
                    ),
                ),
            ],
        ),
    ]
