# Generated by Django 4.1.13 on 2024-11-30 19:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("petapp", "0010_find_lost_pet"),
    ]

    operations = [
        migrations.CreateModel(
            name="Role",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Animal_Shellter",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("house_name", models.CharField(max_length=500, null=True)),
                ("capacity", models.CharField(max_length=500, null=True)),
                ("current_occupancy", models.CharField(max_length=500, null=True)),
                ("address", models.CharField(max_length=500, null=True)),
                ("location", models.CharField(max_length=500, null=True)),
                ("email", models.CharField(max_length=500, null=True)),
                ("owner_name", models.CharField(max_length=500, null=True)),
                ("phone_no", models.CharField(max_length=500, null=True)),
                ("created_at", models.DateTimeField(null=True)),
                ("updated_at", models.DateTimeField(null=True)),
                ("delete", models.BooleanField(default=False, null=True)),
                (
                    "user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="petapp.appuser"
                    ),
                ),
            ],
        ),
    ]
