# Generated by Django 4.1.13 on 2024-11-30 19:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("petapp", "0011_role_animal_shellter"),
    ]

    operations = [
        migrations.AddField(
            model_name="appuser",
            name="role_id",
            field=models.ForeignKey(
                default=2, on_delete=django.db.models.deletion.CASCADE, to="petapp.role"
            ),
        ),
    ]
