# Generated by Django 4.1.13 on 2024-12-01 07:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("petapp", "0012_appuser_role_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="Vet_Clinic",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=500, null=True)),
                ("address", models.CharField(max_length=500, null=True)),
                ("location", models.CharField(max_length=500, null=True)),
                ("email", models.CharField(max_length=500, null=True)),
                ("phone_no", models.CharField(max_length=500, null=True)),
                ("owner_name", models.CharField(max_length=500, null=True)),
                ("country", models.CharField(max_length=500, null=True)),
                ("created_at", models.DateTimeField(null=True)),
                ("updated_at", models.DateTimeField(null=True)),
                ("delete", models.BooleanField(default=False)),
                (
                    "user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="petapp.appuser"
                    ),
                ),
            ],
        ),
    ]
