# Generated by Django 4.1.13 on 2025-03-10 19:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('petapp', '0013_vet_clinic'),
    ]

    operations = [
        migrations.CreateModel(
            name='POST_ADD',
            fields=[
                ('updated_at', models.DateTimeField(auto_created=True, null=True)),
                ('created_at', models.DateTimeField(auto_created=True, null=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('desc', models.TextField(null=True)),
                ('images', models.JSONField(default=list)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='petapp.appuser')),
            ],
        ),
        migrations.CreateModel(
            name='fcm_token',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('token', models.CharField(max_length=500, null=True)),
                ('enable', models.BooleanField(null=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='petapp.appuser')),
            ],
        ),
    ]
