# Generated by Django 4.1.13 on 2025-03-10 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petapp', '0014_post_add_fcm_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpet',
            name='price',
            field=models.IntegerField(null=True),
        ),
    ]
