# Generated by Django 5.1.3 on 2025-03-24 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petapp', '0015_alter_userpet_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(default='', upload_to='category'),
            preserve_default=False,
        ),
    ]
