# Generated by Django 5.1.3 on 2025-03-27 20:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petapp', '0016_category_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favourite_Profile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.BooleanField(null=True)),
                ('favourite_by', models.CharField(max_length=255, null=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='petapp.appuser')),
            ],
        ),
    ]
