# Generated by Django 5.1.3 on 2025-03-29 09:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petapp', '0017_favourite_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sub_Category',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=500, null=True)),
                ('image', models.ImageField(null=True, upload_to='sub_category')),
                ('categ_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='petapp.category')),
            ],
        ),
    ]
